#!/usr/bin/python3


import re                          # Регулярные выражения.
#import requests                    # Загрузка новостей с сайта.
#from bs4 import BeautifulSoup      # Превращалка html в текст.
import pymorphy2                   # Морфологический анализатор.
#import datetime                    # Новости будем перебирать по дате.
from collections import Counter    # Не считать же частоты самим.
import json
#import math                        # Корень квадратный.


infile='/home/cec/w2v/fixes_handle_only_raw.txt'
outfile='/home/cec/w2v/fixes_handle_only_stemmed.txt'

f = open(infile, 'r')
out=open(outfile, 'w')

line=f.readline()

morph=pymorphy2.MorphAnalyzer() # Создает объект морфоанализатора и загружет словарь.


def stem(text, needPos=None):
    tokens=text.split()
    s=''
    for w in tokens:
        wordform=morph.parse(w)[0]
        s+=str(wordform.normal_form)
        s+=' '
    return s

def stempos(text, needPos=None):
  words=[a[0] for a in re.findall("([А-ЯЁа-яё]+(-[А-ЯЁа-яё]+)*)", text)]
  reswords=[]
  for w in words:
    wordform=morph.parse(w)[0]
    if wordform.tag.POS in ['ADJF', 'NOUN', 'VERB']:
      reswords.append(wordform.normal_form + '_' + str(wordform.tag.POS))
  return reswords


count=0
with open(infile) as f:
  for line in f:
    s=stempos(line)
    line=''
    for w in s:
      line=line + ' ' + w
    line=line[1:]
    print(line)
    #count=count + 1
    #if count > 100:
    #  break
out.close
