#!/usr/bin/perl

use strict;
use warnings;

use Cidig::Peren;

my $p=Cidig::Peren->new({'input'=>'warc',
			 'json_only'=>1,
			 'verbose'=>'1'});
#$p->deal_with_warcs({'only_file'=>'rnp/ppaper/nvg155.warc'});
$p->deal_with_warcs();

#$p->parscit_texts();
